---
- hosts: zabbix-hosts
  become: true
  vars:
    zabbix_agent_type: passive

  tasks:
    - name: Install the RPM for x86_64
      yum:
        name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
      when: ansible_architecture == "x86_64"

    - name: Copy the repo file for ppc64le zabbix agent.
      get_url:
        url: http://mochat.massopen.cloud/repos/ppc64le-zabbix-4.repo
        dest: /etc/yum.repos.d/ppc64le-zabbix-4.repo
      when: ansible_architecture == "ppc64le"

    - name: Install zabbix agent
      yum:
        name: zabbix-agent
        state: latest
        update_cache: true

    - name: Install zabbix agent configuration
      copy:
        src: agent_config_files/{{ zabbix_agent_type }}.conf
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - Restart Zabbix

    - name: Start and enable zabbix agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes

  handlers:
    - name: Restart Zabbix
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
